### ISSUE TITLE
Initial backend setup

### ISSUE THREAD

**Issue by divlogic** [codefordenver/energy-assistance-dashboard#2]
### Description
This is just to put the framework in the repo so that everyone has the same thing to work with. 

### Acceptance Criteria
- [x] There's a backend directory that has all the project's ~~flask~~ FastAPI files.  https://fastapi.tiangolo.com/
- [x] Add some basic setup instructions to the readme for getting the project running.

**Comment by pjhoberman** [comment]
I got the server running locally - that feels like acceptance to me!

**Comment by jberns** [comment]
Closed by #12 and #13
