### ISSUE TITLE
Create a component that will display the "Main Overview" table

### ISSUE THREAD

**Issue by divlogic** [codefordenver/energy-assistance-dashboard#4]
### Description
On the [v1](https://docs.google.com/spreadsheets/d/1e6nSz5Mw8kloFNkSN-xi2IjnSP_pclgJy7U1C1fBx68/edit#gid=1220455929) spreadsheet there's a three row table at the top of the page. Create a react component that can take the following data and update what's displayed based on that. Values: Year, low income household count, total households assisted, % of LI Households Assisted.

For now just throw this on the main page with the same default values it has on the v1 sheet. 

### Acceptance Criteria
 - [ ] A new component is created that looks the same as on the v1 sheet.
- [ ] Takes 4 props
- Year
- low income household count 
- total households assisted
- % of LI Households Assisted
- [ ] Printer friendly. To test this out, use your browser's print to pdf functionality.

**Comment by darjama** [comment]
If this is open to anyone to help with, I wouldn't mind working on it.
