### ISSUE TITLE
Create Design for Home (index) page

### ISSUE THREAD

**Issue by jberns** [codefordenver/energy-assistance-dashboard#61]

**Comment by anotherpatrickcollins** [comment]
Designs created in Figma

https://www.figma.com/file/Pyn4X8QAenF1GKwIaeulp6/EOC-Dashboard?node-id=0%3A1

**Comment by anotherpatrickcollins** [comment]
Logo assets for design.
![EOC_Tag_300px](https://user-images.githubusercontent.com/17071865/93946729-456b4100-fcf7-11ea-8aa4-f8acf13b8578.png)
![Horizontal Logo_red](https://user-images.githubusercontent.com/17071865/93946763-5c119800-fcf7-11ea-97b3-31ba286fce75.png)

Icon for design.
![noun_1288241_fcb61a](https://user-images.githubusercontent.com/17071865/93946782-6c297780-fcf7-11ea-928b-1f3d8bd8f326.png)
