### ISSUE TITLE
Implement home page

### ISSUE THREAD

**Issue by jberns** [codefordenver/energy-assistance-dashboard#65]
Waiting on #61

**Comment by anotherpatrickcollins** [comment]
_Content_

In Colorado, thousands of families can’t afford to pay their energy bills. Living in Energy Poverty is a modern burden. The State of Colorado’s Department of Human Services and Energy Outreach Colorado are trying to solve the problem, but your State, your county, and your neighbors still  need more help. Explore the data to see how energy assistance is provided in your county and statewide.

Explore The Data

If you are living with the burden of not being able to afford your energy bills, we can help.

Get Help
