### ISSUE TITLE
Counties Data Endpoint

### ISSUE THREAD

**Issue by jberns** [codefordenver/energy-assistance-dashboard#8]
## Description
Create an Endpoint that accepts a county as a path parameter and then returns that data set.

https://fastapi.tiangolo.com/tutorial/path-params/

REST Types: GET

Input Parameters: {county_name}

URL: /counties/{county_name}

## Acceptance Criteria
- [x] Returns: JSON object of that county's data
- [x] Add a sample JSON output to issue #5 for a front end developer to review.

**Comment by pjhoberman** [comment]
#7 stated that county data should include the county ID. Should we allow GET county/{county name} and GET county/{county ID}?

**Comment by jberns** [comment]
I updated the code so it is ID for now, I don't think the name version will be required in the long term.
