### ISSUE TITLE
County Exception Handling

### ISSUE THREAD

**Issue by jberns** [codefordenver/energy-assistance-dashboard#9]
Setup error handling to check if a county and its data exist before executing the full fetch calculation.

If the county does not exist return a 404 error stating "Requested county does not exist"

https://fastapi.tiangolo.com/tutorial/handling-errors/

**Comment by pjhoberman** [comment]
Is this completed by the work done in #8? Commented in code below

```
@app.get("/counties/{county_id}")
async def get_county_data(county_id: str):
    if county_id in county_list:  # <-- here
        county: str = county_list[county_id]
        county_data: pd.DataFrame = getData(county)
        return {"data": county_data}
    
    raise HTTPException(status_code=404, detail="County not found in database")  # <-- and here
```

**Comment by jberns** [comment]
Oh yep.  Meant to close this with the pull request!
